/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author WINDOWS 10
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Petugas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        In_username = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        In_password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1046, 702));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("LOGIN APLIKASI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 550, 90));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Petugas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 5, true));

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Password");

        In_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit.setText("Login");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        In_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        In_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                In_passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PetugasLayout = new javax.swing.GroupLayout(Petugas);
        Petugas.setLayout(PetugasLayout);
        PetugasLayout.setHorizontalGroup(
            PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PetugasLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PetugasLayout.createSequentialGroup()
                        .addComponent(In_password, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PetugasLayout.createSequentialGroup()
                        .addGroup(PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PetugasLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel2))
                            .addComponent(In_username, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PetugasLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel3))
                            .addGroup(PetugasLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45))))
        );
        PetugasLayout.setVerticalGroup(
            PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PetugasLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(In_username, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(In_password, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        jPanel2.add(Petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 550, 510));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
//        String user = In_username.getText();
//        String pass = In_password.getText();
//
//        try {
//            Statement st = con.createStatement();
//            String sql = "SELECT * FROM  tbl_user where Nama_user='" + user + "' and Pass='" + pass + "'";
//            rs = st.executeQuery(sql);
//
//            if (rs.next()) {
//                String id = rs.getString("Kode_user");
//                String username = rs.getString("Nama_user");
//                String level = rs.getString("level");
//
//                //set user data session
//                UserSession.set_id(id);
//                UserSession.set_username(username);
//                UserSession.set_level(level);
//
//                switch (level) {
//                    case "admin": {
//                        JOptionPane.showMessageDialog(null, "Selamat datang " + username + " !");
//                        Dashboard dsb = new Dashboard();
//                        dsb.dashAdmin();
//                        dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                        dsb.setVisible(true);
//                        dispose();
//                        break;
//                    }
//                    case "petugas": {
//                        JOptionPane.showMessageDialog(null, "Selamat datang " + username + " !");
//                        Dashboard dsb = new Dashboard();
//                        dsb.dashPetugas();
//                        dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                        dsb.setVisible(true);
//                        dispose();
//                        break;
//                    }
//                    default:
//                    break;
//                }
//
//            } else {
//                JOptionPane.showMessageDialog(null, "Username atau password salah");
//            }
//        } catch (SQLException e) {
//            System.out.println(e);
//        }
    }//GEN-LAST:event_submitMouseEntered

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
////        String user = In_username.getText();
////        String pass = In_password.getText();
////
////        try {
////            Statement st = con.createStatement();
////            String sql = "SELECT * FROM  tbl_user where Nama_user='" + user + "' and Pass='" + pass + "'";
////            rs = st.executeQuery(sql);
////
////            if (rs.next()) {
////                String id = rs.getString("Kode_user");
////                String username = rs.getString("Nama_user");
////                String level = rs.getString("level");
////
////                //set user data session
////                UserSession.set_id(id);
////                UserSession.set_username(username);
////                UserSession.set_level(level);
////
////                switch (level) {
////                    case "admin": {
////                        JOptionPane.showMessageDialog(null, "Selamat datang " + username + " !");
////                        Dashboard dsb = new Dashboard();
////                        dsb.dashAdmin();
////                        dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
////                        dsb.setVisible(true);
////                        dispose();
////                        break;
////                    }
////                    case "petugas": {
////                        JOptionPane.showMessageDialog(null, "Selamat datang " + username + " !");
////                        Dashboard dsb = new Dashboard();
////                        dsb.dashPetugas();
////                        dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
////                        dsb.setVisible(true);
////                        dispose();
////                        break;
////                    }
////                    default:
////                    break;
////                }
////
////            } else {
////                JOptionPane.showMessageDialog(null, "Username atau password salah");
////            }
////        } catch (SQLException e) {
////            System.out.println(e);
////        }
        new dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_submitActionPerformed

    private void In_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_In_passwordActionPerformed
//        String user = In_username.getText();
//        String pass = In_password.getText();
//
//        try {
//            Statement st = con.createStatement();
//            String sql = "SELECT * FROM  tbl_user where Nama_user='" + user + "' and Pass='" + pass + "'";
//            rs = st.executeQuery(sql);
//
//            if (rs.next()) {
//                String id = rs.getString("Kode_user");
//                String username = rs.getString("Nama_user");
//                String level = rs.getString("level");
//
//                //set user data session
//                UserSession.set_id(id);
//                UserSession.set_username(username);
//                UserSession.set_level(level);
//
//                switch (level) {
//                    case "admin": {
//                        JOptionPane.showMessageDialog(null, "Selamat datang " + username + " !");
//                        Dashboard dsb = new Dashboard();
//                        dsb.dashAdmin();
//                        dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                        dsb.setVisible(true);
//                        dispose();
//                        break;
//                    }
//                    case "petugas": {
//                        JOptionPane.showMessageDialog(null, "Selamat datang " + username + " !");
//                        Dashboard dsb = new Dashboard();
//                        dsb.dashPetugas();
//                        dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                        dsb.setVisible(true);
//                        dispose();
//                        break;
//                    }
//                    default:
//                    break;
//                }
//
//            } else {
//                JOptionPane.showMessageDialog(null, "Username atau password salah");
//            }
//        } catch (SQLException e) {
//            System.out.println(e);
//        }
    }//GEN-LAST:event_In_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField In_password;
    private javax.swing.JTextField In_username;
    private javax.swing.JPanel Petugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
